# Generated by Django 4.2.1 on 2023-05-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0003_dataentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='added',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='end_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='impact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='insight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='intensity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='likelihood',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='pestle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='published',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='relevance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='sector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='start_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
