# Generated by Django 4.2.1 on 2023-05-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0004_alter_dataentry_added_alter_dataentry_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='published',
            field=models.DateTimeField(),
        ),
    ]
